version: '3'

# Runs the Django development server, which is less than ideal in terms of
# replicating the deployment environment locally -- for which, the
# docker-compose-local.yml file is provided. However, due to lack of a good solution
# for static file development in a more deployment-like configuration, this
# current compose file is provided for development.

# web service mount to apps location so that development updates in the application
# are reflected in the container.

# Note: the db build will create the default postgres database and user. To
# create the application database, run `initdb.sh` after building.

services:
  app:
    restart: always
    build: .
    ports:
      - "80:5000"
    links:
      - mongo:mongo
    volumes:
      - .:/usr/src/apps/StoryMapJS
    env_file: .env
    command: python api.py -p 5000
    depends_on:
      - mongo

  mongo:
    image: mongo:2.4
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - "27017-27019:27017-27019"
      - "28017:28017"
    environment:
      MONGO_INITDB_DATABASE: storymapjs



volumes:
  mongodata:
