version: '3'

services:

  app:
    build: .
    env_file: .env
    restart: always
    volumes:
      - .:/usr/src/apps/StoryMapJS
      - /var/www/StoryMapJS:/var/www/StoryMapJS
    environment:
      DEBUG: 'true'
      PYTHONPATH: .
    command: gunicorn --workers 3 --worker-tmp-dir /dev/shm --bind unix:/usr/src/apps/StoryMapJS/mnt/StoryMapJS.sock core.wsgi:application

volumes:
  web-django:
  web-static:
