version: '3'

# The default docker-compose file for local development

# Usage:
#
#  $ docker-compose build
#  $ docker-compose up
#
#  Navigate to https://localhost
#
# See QUICKSTART.md for preliminaries before running this stack.

# Runs the Flask development server. This stack is sufficient for most
# development needs and so is the default docker-compose option.

services:

  app:
    restart: always
    build: .
    ports:
      - "443:5000"
    links:
      - pg:pg
      - localstack:localstack
    volumes:
      - ./storymap:/usr/src/apps/StoryMapJS/storymap
      - ./dist:/usr/src/apps/StoryMapJS/dist
    #  #- ./.localstack/:/usr/src/apps/StoryMapJS/.localstack
    env_file: .env
    command: gunicorn -b :5000 --workers 1 --reload storymap.core.wsgi:application --keyfile server.test.pem.key --certfile server.test.pem.crt
    depends_on:
      - pg
      - localstack

  pg:
    image: postgres:11.6
    restart: always
    environment:
      POSTGRES_USER: storymap
      POSTGRES_DB: storymap
      POSTGRES_PASSWORD: storymap
    ports:
      - "5432:5432"
    volumes:
      - ./.pgdata/:/var/lib/postgresql/data/

  localstack:
    image: localstack/localstack-light
    restart: always
    environment:
      USE_LIGHT_IMAGE: 1
      LOCALSTACK_SERVICES: s3
      DATA_DIR: /tmp/localstack/data
    ports:
      - "4566:4566"
    volumes:
      - ./.localstack/:/tmp/localstack
      #- /var/run/docker.sock:/var/run/docker.sock

