domains: "storymap.knightlab.com"
cnames: "storymapjs.knightlab.com"

init_env_prd:
  CDN_URL: "//cdn.knightlab.com/libs/storymapjs/latest/"

init_env: "{{ init_env_common|combine(init_env_prd) }}"
service_exec: "{{ virtualenv}}/bin/gunicorn -b :{{ service_port }} --workers 3 {{ wsgi_application }}"
